### ISSUE TITLE
[bootloader] support bootc-style /boot directory layout

### ISSUE THREAD

**Issue by bmr-cymru** [snapshotmanager/boom#74]
When bootc is used to deploy a system in image mode the kernel and initramfs images are stored at paths like:

```
        linux /boot/ostree/default-0daf2e3947ecc351d2fe1f71e2e2498af74a7fd4be3e007a984092b823b32f47/vmlinuz-6.11.0-0.rc5.23.el10.x86_64
        initrd /boot/ostree/default-0daf2e3947ecc351d2fe1f71e2e2498af74a7fd4be3e007a984092b823b32f47/initramfs-6.11.0-0.rc5.23.el10.x86_64.img
```

The SHA256 value in the path corresponds to the structure of the ` /ostree/boot.1/default/<HASH>/0`directory and the `ostree=` kernel command line parameter - it's not completely clear what this value represents. It does not appear to be reported by the `bootc`/`rpm-ostree` command line tools:

```
[root@localhost ~]# bootc status
apiVersion: org.containers.bootc/v1
kind: BootcHost
metadata:
  name: host
spec:
  image:
    image: localhost/rhel10-test1:latest
    transport: registry
  bootOrder: default
status:
  staged: null
  booted:
    image:
      image:
        image: localhost/rhel10-test1:latest
        transport: registry
      version: 10.20250116.0
      timestamp: null
      imageDigest: sha256:41cd22309b7ff1200b1f26e3567717864de3d5d420036f008f4648c3b59b98a7
    cachedUpdate: null
    incompatible: false
    pinned: false
    store: ostreeContainer
    ostree:
      checksum: 9ae97b6d3796af0414a3fe026cf3ce2dc66f01990ea33259e8244ef03c788fe5
      deploySerial: 0
  rollback: null
  rollbackQueued: false
  type: bootcHost
```

```
[root@localhost ~]# rpm-ostree status -v
State: idle
AutomaticUpdates: disabled
Deployments:
● ostree-unverified-registry:localhost/rhel10-test1:latest (index: 0)
                   Digest: sha256:41cd22309b7ff1200b1f26e3567717864de3d5d420036f008f4648c3b59b98a7
                  Version: 10.20250116.0 (2025-02-27T20:23:49Z)
                   Commit: 9ae97b6d3796af0414a3fe026cf3ce2dc66f01990ea33259e8244ef03c788fe5
                   Staged: no
                StateRoot: default
```
